name = "sentinel-url-inspector"
main = "src/index.ts"
compatibility_date = "2026-07-22"
workers_dev = true
preview_urls = false
keep_vars = true

[[ratelimits]]
name = "URL_CHECK_RATE_LIMITER"
namespace_id = "104729"

  [ratelimits.simple]
  limit = 10
  period = 60
